# Portfolio assignment 5 {.tabset .unnumbered}
## Assignment {.unnumbered}

__A__ <br>
Make sure you have:<br>
1. Two personal repositories on github: one for your portfolio, one for the regular exercises.<br>
2. One repo in the projecticum organisation, that you share with your partner.<br>
3. Your local repositories are up to date with the main for all three of them.<br>
4. A github project, with kanban board filled with issues connected to the projecticum repository.<br>
5. One (separate!) .Rmd file for each of your projecticum assignments.<br>
6. Three local (i.e. on your laptop) Rstudio projects: projecticum, portfolio and regular_assignments. (you may have given them other names, that’s fine)

__B__<br>
1. Make a new folder within Mendeley for the projecticum. Place all pdf’s you used till now in your folder (if you did not use any papers as source yet, find 3 papers on Pubmed now that you could use for your introduction.). Copy your .bib file to the folder on your computer you are using for the Projecticum git repo.<br>
2. Start a .Rmd named “introduction.Rmd” with a few lines introduction on your projecticum topic.<br>
3. Include automatic inline references to the papers you used.<br>
4. The bibliography will be placed at the end of the document. Provide an appropriate header.<br>
5. Merge your work with that of your projecticum partner through github. Solve all the problems you encounter. If github does not want to merge .bib files and you want a merged one, try here.<br>
6. Find out how you can add websites as reference to Mendeley.<br>
7. Write (so not “copy!”) at least 500 words of introduction for your projecticum project and use at least 5 references.

## Projecticum introduction {.unnumbered}

[View here](./data/_introduction.html)