---
title: "R portfolio Daniël Roodzant"
author: "Daniël Roodzant"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
new_session: yes
output:
  bookdown::gitbook:
    number_sections: true
    split_by: chapter 
    config:
      toc:
        collapse: section
        scroll_highlights: yes
  #bookdown::pdf_book: default
bibliography: data/data_raw/bibliography_pmc_proj.bib
theme: jekyll-theme-cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl) 
library(lubridate)
library(fs)
library(dplyr)
library(dslabs)
library(here)
library(htmltools)
```

Introduction {.unnumbered}
================================================================================
Welcome to my bookdown portfolio. Here I will show you some of the coding skills I have gathered.

Lets start with my CV which I have created using the pagedown package: <br>
[My CV](https://datascience.hu.nl/rstudio/tlsc-dsfb16v-20-21/files/shared/data/DanielRoodzant/dsfb2_workflows_portfolio/data/_CV_Dani%C3%ABl_Roodzant.html)

```{r, echo=FALSE}
htmltools::includeHTML("data/_CV_Daniël_Roodzant.html")
```
