---
title: "Daniël Roodzant's CV"
author: Daniël Roodzant
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================
Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> daniel.roodzant@hotmail.com
- <i class="fa fa-github"></i> [github.com/DanielRoodzantHU](https://github.com/DanielRoodzantHU)
- <i class="fa fa-phone"></i> +31 6 577 788 38
- Meer informatie via email. 

Vaardigheden {#skills}
--------------------------------------------------------------------------------
<p style="text-align: right;">
MS Office <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="far fa-circle"></i></p>
<p style="text-align: right;">
Bash, Perl, R, R-Shiny    <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="far fa-circle"></i><i class="far fa-circle"></i></p><br>
<p style="text-align: right;">
Teamwork    <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="far fa-circle"></i></p>
<p style="text-align: right;">
Aanpassingsvermogen     <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="far fa-circle"></i></p>
<p style="text-align: right;">
Leiderschap     <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="far fa-circle"></i></p>

Talen {#skills}
--------------------------------------------------------------------------------
<p style="text-align: right;">
Nederlands <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i></p>
<p style="text-align: right;">
Engels <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="fas fa-circle"></i></p>
<p style="text-align: right;">
Duits <i class="fas fa-circle"></i><i class="fas fa-circle"></i><i class="far fa-circle"></i><i class="far fa-circle"></i><i class="far fa-circle"></i></p>

Hobby's en intresses {#skills}
--------------------------------------------------------------------------------
- Lezen van non-fictie boeken
- Drummen in mijn vrije tijd
- Sporten in de sportschool
- Leren beleggen


Main
================================================================================

Daniël Roodzant {#title}
--------------------------------------------------------------------------------

### Persoonlijk profiel
Ik ben een gedreven en leergierige biotechnologisch analist met ambitie voor data-science. Ik pak graag grote probleemstukken aan en houd ervan om mij te verdiepen in het ‘waarom’. Nieuwe dingen leren en mijn kennis en vaardigheden verbeteren vind ik erg belangrijk.


Onderwijs {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### B-Life Sciences, Hogeschool Utrecht

Specialitsatie Biomolecular Research

Utrecht

heden - 2018

### Minor Data Sciences for Biology, Hogeschool Utrecht

Focus: (Big)Dataverwerking met bash en R.

Utrecht

heden - 2021

### Biotechnologisch Analist niveau 4, ROC van Amsterdam

Bijzonderheden: Cum laude diploma behaald en opleiding één jaar verkort afgerond

Amsterdam

jul 2018 - Sep 2015

### Havo – Natuur en Gezondheid, Willem de Zwijger College Bussum

Bijzonderheden: Geen diploma behaald

Bussum

jul 2015 - Sep 2010

Werkervaring {data-icon=suitcase}
--------------------------------------------------------------------------------

### Verkoopmedewerker

Dierenwinkel Krans

Hilversum

heden - Jul 2017

::: concise
- Specifiek klantenadvies verzorgen
::: 

### Stagiair diagnostisch- en onderzoeksanalist op afdeling endocrinologie

Universitaire Medische Centra

Amsterdam

jun 2018 - Mar 2017

::: concise
- GCMS
- Patiënten-monsters hanteren
- Diagnostische bepalingen uitvoeren
::: 

### Verkoopmedewerker
 
Lidl supermarkten

Hilversum

Feb 2017 - Feb 2016

### Vakkenvuller

Albert Heijn supermarkten

Laren

Dec 2015 - 2013

<br>
<br>
<br>
<br>
<br>
<br>
This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown). <br>
Last updated on `r Sys.Date()`.
